#
# This dockerfile is used only to build a new release for production
# Take a look at Makefile or run "make help"
#
# Run
# $ make release.prod


FROM nginx:alpine

COPY build /usr/share/nginx/html
